#!/usr/bin/env fish

set script_path (status --current-filename)
set test_dir (dirname "$script_path")
set root_dir (realpath "$test_dir/../../..")
set generator "$root_dir/scripts/spectra-plus/generate.fish"
set rules "$root_dir/scripts/spectra-plus/rules.yaml"
set propose "$root_dir/.claude/skills/spectra-propose-plus/SKILL.md"
set apply "$root_dir/.claude/skills/spectra-apply-plus/SKILL.md"
set marker "<!-- Generated by scripts/spectra-plus/generate.fish — DO NOT EDIT MANUALLY -->"

function fail
    echo "FAIL: $argv" >&2
    exit 1
end

function assert_contains
    set file $argv[1]
    set text $argv[2]
    rg -q --fixed-strings "$text" "$file"; or fail "$file missing $text"
end

function assert_not_contains
    set file $argv[1]
    set text $argv[2]
    if rg -q --fixed-strings "$text" "$file"
        fail "$file unexpectedly contains $text"
    end
end

function run_expect
    set expected $argv[1]
    set command $argv[2..-1]
    $command >/tmp/spectra-plus-test.out 2>/tmp/spectra-plus-test.err
    set actual $status
    test "$actual" -eq "$expected"; or begin
        cat /tmp/spectra-plus-test.out
        cat /tmp/spectra-plus-test.err >&2
        fail "expected exit $expected, got $actual: $command"
    end
end

cd "$root_dir"; or fail "cannot cd to root"

yq '.' "$rules" >/dev/null; or fail "rules.yaml did not parse"

run_expect 0 "$generator" --help
run_expect 0 "$generator"

test -f "$propose"; or fail "missing propose plus output"
test -f "$apply"; or fail "missing apply plus output"
test (head -n 1 "$propose") = "$marker"; or fail "propose marker mismatch"
test (head -n 1 "$apply") = "$marker"; or fail "apply marker mismatch"

assert_contains "$propose" "name: spectra-propose-plus"
assert_contains "$apply" "name: spectra-apply-plus"
assert_not_contains "$propose" "spectra park"
assert_contains "$propose" "review/rating/fix"
assert_contains "$apply" "review/rating/fix"
assert_contains "$apply" "ai 的回覆要用中文"

command cp -f "$propose" /tmp/spectra-propose-plus.before
command cp -f "$apply" /tmp/spectra-apply-plus.before
run_expect 0 "$generator"
diff -u /tmp/spectra-propose-plus.before "$propose"; or fail "propose output not idempotent"
diff -u /tmp/spectra-apply-plus.before "$apply"; or fail "apply output not idempotent"

set before_apply_mtime (stat -f %m "$apply")
sleep 1
run_expect 0 "$generator" spectra-propose-plus
set after_apply_mtime (stat -f %m "$apply")
test "$before_apply_mtime" = "$after_apply_mtime"; or fail "single-skill regeneration touched apply output"

echo "MANUAL_EDIT_SENTINEL" >> "$propose"
run_expect 0 "$generator" spectra-propose-plus
assert_not_contains "$propose" "MANUAL_EDIT_SENTINEL"

command cp -f "$rules" /tmp/spectra-plus-rules.backup

set restore_rules "command cp -f /tmp/spectra-plus-rules.backup $rules"

yq '.skills."spectra-propose-plus".transformations[0].target_section = "missing target section"' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 1 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing target section"
eval $restore_rules

yq '.skills."spectra-propose-plus".transformations[0].template = "missing-template.md"' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 3 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing-template.md"
eval $restore_rules

yq 'del(.skills."spectra-propose-plus".source)' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 2 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "source"
eval $restore_rules

run_expect 0 "$generator"
echo "PASS: generator checks"
