#!/usr/bin/env fish

set script_path (status --current-filename)
set test_dir (dirname "$script_path")
set root_dir (realpath "$test_dir/../../..")
set generator "$root_dir/scripts/spectra-plus/generate.fish"
set rules "$root_dir/scripts/spectra-plus/rules.yaml"
set propose "$root_dir/.claude/skills/spectra-propose-plus/SKILL.md"
set apply "$root_dir/.claude/skills/spectra-apply-plus/SKILL.md"
set propose_codex "$root_dir/.agents/skills/spectra-propose-plus/SKILL.md"
set apply_codex "$root_dir/.agents/skills/spectra-apply-plus/SKILL.md"
set propose_outputs "$propose" "$propose_codex"
set apply_outputs "$apply" "$apply_codex"
set all_outputs $propose_outputs $apply_outputs
set marker "<!-- Generated by scripts/spectra-plus/generate.fish — DO NOT EDIT MANUALLY -->"
set plus_version "1.1.0"
set plus_updated "2026-07-04"

function fail
    echo "FAIL: $argv" >&2
    exit 1
end

function assert_contains
    set file $argv[1]
    set text $argv[2]
    rg -q --fixed-strings "$text" "$file"; or fail "$file missing $text"
end

function assert_not_contains
    set file $argv[1]
    set text $argv[2]
    if rg -q --fixed-strings "$text" "$file"
        fail "$file unexpectedly contains $text"
    end
end

function assert_not_contains_i
    set file $argv[1]
    set text $argv[2]
    if rg -qi --fixed-strings "$text" "$file"
        fail "$file unexpectedly contains (case-insensitive) $text"
    end
end

function first_line_number
    set file $argv[1]
    set text $argv[2]
    rg -n --fixed-strings "$text" "$file" | head -n 1 | cut -d: -f1
end

function assert_line_order
    set file $argv[1]
    set first $argv[2]
    set second $argv[3]
    set first_line (first_line_number "$file" "$first")
    set second_line (first_line_number "$file" "$second")
    test -n "$first_line"; or fail "$file missing order anchor $first"
    test -n "$second_line"; or fail "$file missing order anchor $second"
    test "$first_line" -lt "$second_line"; or fail "$file expected $first before $second"
end

function assert_step_numbers_sequential
    set file $argv[1]
    awk '
        /^[0-9]+\. \*\*/ {
            expected++
            actual = $1
            sub(/\.$/, "", actual)
            if (actual != expected) {
                printf("step numbering mismatch: expected %d got %s at line %d\n", expected, actual, NR) > "/dev/stderr"
                exit 1
            }
        }
    ' "$file"; or fail "$file has non-sequential step numbering"
end

function assert_frontmatter_contains
    set file $argv[1]
    set text $argv[2]
    awk -v text="$text" '
        NR == 1 && $0 == "---" { in_fm = 1; next }
        in_fm && $0 == "---" { exit }
        in_fm && $0 == text { found = 1; exit }
        END { exit found ? 0 : 1 }
    ' "$file"; or fail "$file frontmatter missing $text"
end

function output_fingerprint
    for file in $all_outputs
        cksum "$file"
    end
end

function run_expect
    set expected $argv[1]
    set command $argv[2..-1]
    $command >/tmp/spectra-plus-test.out 2>/tmp/spectra-plus-test.err
    set actual $status
    test "$actual" -eq "$expected"; or begin
        cat /tmp/spectra-plus-test.out
        cat /tmp/spectra-plus-test.err >&2
        fail "expected exit $expected, got $actual: $command"
    end
end

function run_with_bad_rules_expect
    set expected $argv[1]
    set bad_rules $argv[2]
    set command $argv[3..-1]
    command cp -f "$rules" /tmp/spectra-plus-rules.backup
    command cp -f "$bad_rules" "$rules"
    $command >/tmp/spectra-plus-test.out 2>/tmp/spectra-plus-test.err
    set actual $status
    command cp -f /tmp/spectra-plus-rules.backup "$rules"
    test "$actual" -eq "$expected"; or begin
        cat /tmp/spectra-plus-test.out
        cat /tmp/spectra-plus-test.err >&2
        fail "expected exit $expected, got $actual: $command"
    end
end

cd "$root_dir"; or fail "cannot cd to root"

yq '.' "$rules" >/dev/null; or fail "rules.yaml did not parse"

run_expect 0 "$generator" --help
run_expect 0 "$generator"

test -f "$propose"; or fail "missing propose plus output"
test -f "$apply"; or fail "missing apply plus output"
assert_contains "$propose" "$marker"
assert_contains "$apply" "$marker"

assert_contains "$propose" "name: spectra-propose-plus"
assert_contains "$apply" "name: spectra-apply-plus"
for skill_path in $all_outputs
    assert_frontmatter_contains "$skill_path" "spectraPlusVersion: $plus_version"
    assert_frontmatter_contains "$skill_path" "spectraPlusUpdated: $plus_updated"
end
assert_not_contains "$propose" "spectra park"
assert_contains "$propose" "review/rating/fix"
assert_contains "$apply" "review/rating/fix"
assert_contains "$apply" "ai 的回覆要用中文"
assert_contains "$apply" "Implementation Notes Protocol"
assert_contains "$apply" "implementation-notes.md"
assert_not_contains "$propose" "Implementation Notes Protocol"

# Parallel reviewers + confidence filter behavior — both plus skills share review-loop-block
# Assert across both claude and codex variants to lock template + rules behavior.
for skill_path in $propose_outputs $apply_outputs
    assert_contains "$skill_path" "Reviewer A — Adherence"
    assert_contains "$skill_path" "Reviewer B — Quality"
    assert_contains "$skill_path" "Confidence scoring rubric"
    assert_contains "$skill_path" "Confidence filter"
    assert_contains "$skill_path" "Common false positives"
    assert_contains "$skill_path" "Direct artifact-requirement violations MUST score"
    # Rater removed: no rater sub-agent role and no quality_score field in any variant.
    assert_not_contains_i "$skill_path" "rater"
    assert_not_contains "$skill_path" "quality_score"
    # Mechanical decision rule derived by the main agent after the confidence filter.
    assert_contains "$skill_path" "surviving Critical"
    assert_contains "$skill_path" "surviving Warning"
    assert_step_numbers_sequential "$skill_path"
    assert_not_contains "$skill_path" "docs/specs/"
    assert_not_contains "$skill_path" "Codex Plan Mode"
    assert_not_contains "$skill_path" "ExitPlanMode"
    assert_not_contains "$skill_path" "EnterPlanMode"
end

for skill_path in $propose_outputs
    assert_line_order "$skill_path" "8. **Validation**" "9. **Sub-Agent Review/Rating/Fix Loop**"
    assert_line_order "$skill_path" "9. **Sub-Agent Review/Rating/Fix Loop**" "10. **Finish the plus proposal workflow**"
    assert_contains "$skill_path" "has passed. If validation fixes are required, complete them before entering this loop."
    assert_contains "$skill_path" "if any fix action modifies proposal, design, tasks, or spec artifacts, run `spectra validate \"<name>\"` again"
end

for skill_path in $apply_outputs
    assert_line_order "$skill_path" "Surgical & Simplicity Discipline" "8. **Implementation Notes Protocol**"
    assert_line_order "$skill_path" "8. **Implementation Notes Protocol**" "9. **Final check**"
    assert_contains "$skill_path" "Reviewer A — Adherence in the Sub-Agent Review/Rating/Fix Loop MUST"
    assert_contains "$skill_path" "archive guidance is deferred until the plus quality gate passes"
    assert_contains "$skill_path" "All tasks complete. The plus quality gate runs next; archive guidance is shown only if it passes."
    assert_contains "$skill_path" "Do not suggest archive before the Sub-Agent Review/Rating/Fix Loop has ended with `decision: passed`."
    assert_not_contains "$skill_path" "The review-loop reviewer"
    assert_not_contains "$skill_path" "Section 10"
    assert_not_contains "$skill_path" "step 11"
    assert_not_contains "$skill_path" "All tasks complete! You can archive this change with"
end

# Signals shared layer — write step in both plus skills (all variants), read step in propose-plus only.
# Also assert the DO NOT EDIT marker survives in all four variants (not just the claude ones).
for skill_path in $propose_outputs $apply_outputs
    assert_contains "$skill_path" "<!-- SIGNALS-WRITE-STEP -->"
    assert_contains "$skill_path" "$marker"
end
for skill_path in $propose_outputs
    assert_contains "$skill_path" "<!-- SIGNALS-READ-STEP -->"
end
for skill_path in $apply_outputs
    assert_not_contains "$skill_path" "<!-- SIGNALS-READ-STEP -->"
end

# Surgical & Simplicity discipline — apply-plus only (both variants)
for skill_path in $apply_outputs
    assert_contains "$skill_path" "Surgical & Simplicity Discipline"
    assert_contains "$skill_path" "Simplicity First"
    assert_contains "$skill_path" "Surgical Changes"
    assert_contains "$skill_path" "Maintain Balance"
end
for skill_path in $propose_outputs
    assert_not_contains "$skill_path" "Surgical & Simplicity Discipline"
    assert_not_contains "$skill_path" "Maintain Balance"
end

command cp -f "$propose" /tmp/spectra-propose-plus.before
command cp -f "$apply" /tmp/spectra-apply-plus.before
run_expect 0 "$generator"
diff -u /tmp/spectra-propose-plus.before "$propose"; or fail "propose output not idempotent"
diff -u /tmp/spectra-apply-plus.before "$apply"; or fail "apply output not idempotent"

set before_apply_mtime (stat -f %m "$apply")
set before_apply_codex_mtime (stat -f %m "$apply_codex")
sleep 1
run_expect 0 "$generator" spectra-propose-plus
set after_apply_mtime (stat -f %m "$apply")
set after_apply_codex_mtime (stat -f %m "$apply_codex")
test "$before_apply_mtime" = "$after_apply_mtime"; or fail "single-skill regeneration touched apply output (claude)"
test "$before_apply_codex_mtime" = "$after_apply_codex_mtime"; or fail "single-skill regeneration touched apply output (codex)"

echo "MANUAL_EDIT_SENTINEL" >> "$propose"
run_expect 0 "$generator" spectra-propose-plus
assert_not_contains "$propose" "MANUAL_EDIT_SENTINEL"

yq '.skills."spectra-propose-plus".transformations[0].target_section = "missing target section"' "$rules" > /tmp/spectra-plus-rules.bad
run_with_bad_rules_expect 1 /tmp/spectra-plus-rules.bad "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing target section"

yq '.skills."spectra-propose-plus".transformations[0].template = "missing-template.md"' "$rules" > /tmp/spectra-plus-rules.bad
run_with_bad_rules_expect 3 /tmp/spectra-plus-rules.bad "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing-template.md"

yq 'del(.skills."spectra-propose-plus".variants.codex.source)' "$rules" > /tmp/spectra-plus-rules.bad
run_with_bad_rules_expect 2 /tmp/spectra-plus-rules.bad "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "source"

for mutation in missing-version missing-updated invalid-updated invalid-calendar-updated mismatched-version mismatched-updated null-version empty-version
    set before_failure (output_fingerprint | string collect)

    switch $mutation
        case missing-version
            yq 'del(.skills."spectra-propose-plus".metadata.spectraPlusVersion)' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusVersion"
        case missing-updated
            yq 'del(.skills."spectra-propose-plus".metadata.spectraPlusUpdated)' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusUpdated"
        case invalid-updated
            yq '.skills."spectra-propose-plus".metadata.spectraPlusUpdated = "20260704"' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusUpdated"
        case invalid-calendar-updated
            yq '.skills."spectra-propose-plus".metadata.spectraPlusUpdated = "2026-13-45" | .skills."spectra-apply-plus".metadata.spectraPlusUpdated = "2026-13-45"' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusUpdated"
        case mismatched-version
            yq '.skills."spectra-apply-plus".metadata.spectraPlusVersion = "9.9.9"' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusVersion"
        case mismatched-updated
            yq '.skills."spectra-apply-plus".metadata.spectraPlusUpdated = "2026-01-01"' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusUpdated"
        case null-version
            yq '.skills."spectra-propose-plus".metadata.spectraPlusVersion = null' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusVersion"
        case empty-version
            yq '.skills."spectra-propose-plus".metadata.spectraPlusVersion = ""' "$rules" > /tmp/spectra-plus-rules.bad
            set expected_field "spectraPlusVersion"
    end

    run_with_bad_rules_expect 2 /tmp/spectra-plus-rules.bad "$generator"
    assert_contains /tmp/spectra-plus-test.err "$expected_field"
    set after_failure (output_fingerprint | string collect)
    test "$before_failure" = "$after_failure"; or fail "$mutation partially overwrote generated outputs"
end

run_expect 0 "$generator"
echo "PASS: generator checks"
