#!/usr/bin/env fish

set script_path (status --current-filename)
set test_dir (dirname "$script_path")
set root_dir (realpath "$test_dir/../../..")
set generator "$root_dir/scripts/spectra-plus/generate.fish"
set rules "$root_dir/scripts/spectra-plus/rules.yaml"
set propose "$root_dir/.claude/skills/spectra-propose-plus/SKILL.md"
set apply "$root_dir/.claude/skills/spectra-apply-plus/SKILL.md"
set propose_codex "$root_dir/.agents/skills/spectra-propose-plus/SKILL.md"
set apply_codex "$root_dir/.agents/skills/spectra-apply-plus/SKILL.md"
set propose_outputs "$propose" "$propose_codex"
set apply_outputs "$apply" "$apply_codex"
set marker "<!-- Generated by scripts/spectra-plus/generate.fish — DO NOT EDIT MANUALLY -->"

function fail
    echo "FAIL: $argv" >&2
    exit 1
end

function assert_contains
    set file $argv[1]
    set text $argv[2]
    rg -q --fixed-strings "$text" "$file"; or fail "$file missing $text"
end

function assert_not_contains
    set file $argv[1]
    set text $argv[2]
    if rg -q --fixed-strings "$text" "$file"
        fail "$file unexpectedly contains $text"
    end
end

function run_expect
    set expected $argv[1]
    set command $argv[2..-1]
    $command >/tmp/spectra-plus-test.out 2>/tmp/spectra-plus-test.err
    set actual $status
    test "$actual" -eq "$expected"; or begin
        cat /tmp/spectra-plus-test.out
        cat /tmp/spectra-plus-test.err >&2
        fail "expected exit $expected, got $actual: $command"
    end
end

cd "$root_dir"; or fail "cannot cd to root"

yq '.' "$rules" >/dev/null; or fail "rules.yaml did not parse"

run_expect 0 "$generator" --help
run_expect 0 "$generator"

test -f "$propose"; or fail "missing propose plus output"
test -f "$apply"; or fail "missing apply plus output"
assert_contains "$propose" "$marker"
assert_contains "$apply" "$marker"

assert_contains "$propose" "name: spectra-propose-plus"
assert_contains "$apply" "name: spectra-apply-plus"
assert_not_contains "$propose" "spectra park"
assert_contains "$propose" "review/rating/fix"
assert_contains "$apply" "review/rating/fix"
assert_contains "$apply" "ai 的回覆要用中文"
assert_contains "$apply" "Implementation Notes Protocol"
assert_contains "$apply" "implementation-notes.md"
assert_not_contains "$propose" "Implementation Notes Protocol"

# Parallel reviewers + confidence filter behavior — both plus skills share review-loop-block
# Assert across both claude and codex variants to lock template + rules behavior.
for skill_path in $propose_outputs $apply_outputs
    assert_contains "$skill_path" "Reviewer A — Adherence"
    assert_contains "$skill_path" "Reviewer B — Quality"
    assert_contains "$skill_path" "Confidence scoring rubric"
    assert_contains "$skill_path" "Confidence filter"
    assert_contains "$skill_path" "Common false positives"
    assert_contains "$skill_path" "Direct artifact-requirement violations MUST score"
end

# Surgical & Simplicity discipline — apply-plus only (both variants)
for skill_path in $apply_outputs
    assert_contains "$skill_path" "Surgical & Simplicity Discipline"
    assert_contains "$skill_path" "Simplicity First"
    assert_contains "$skill_path" "Surgical Changes"
    assert_contains "$skill_path" "Maintain Balance"
end
for skill_path in $propose_outputs
    assert_not_contains "$skill_path" "Surgical & Simplicity Discipline"
    assert_not_contains "$skill_path" "Maintain Balance"
end

command cp -f "$propose" /tmp/spectra-propose-plus.before
command cp -f "$apply" /tmp/spectra-apply-plus.before
run_expect 0 "$generator"
diff -u /tmp/spectra-propose-plus.before "$propose"; or fail "propose output not idempotent"
diff -u /tmp/spectra-apply-plus.before "$apply"; or fail "apply output not idempotent"

set before_apply_mtime (stat -f %m "$apply")
set before_apply_codex_mtime (stat -f %m "$apply_codex")
sleep 1
run_expect 0 "$generator" spectra-propose-plus
set after_apply_mtime (stat -f %m "$apply")
set after_apply_codex_mtime (stat -f %m "$apply_codex")
test "$before_apply_mtime" = "$after_apply_mtime"; or fail "single-skill regeneration touched apply output (claude)"
test "$before_apply_codex_mtime" = "$after_apply_codex_mtime"; or fail "single-skill regeneration touched apply output (codex)"

echo "MANUAL_EDIT_SENTINEL" >> "$propose"
run_expect 0 "$generator" spectra-propose-plus
assert_not_contains "$propose" "MANUAL_EDIT_SENTINEL"

command cp -f "$rules" /tmp/spectra-plus-rules.backup

set restore_rules "command cp -f /tmp/spectra-plus-rules.backup $rules"

yq '.skills."spectra-propose-plus".transformations[0].target_section = "missing target section"' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 1 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing target section"
eval $restore_rules

yq '.skills."spectra-propose-plus".transformations[0].template = "missing-template.md"' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 3 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "missing-template.md"
eval $restore_rules

yq 'del(.skills."spectra-propose-plus".variants.codex.source)' "$rules" > /tmp/spectra-plus-rules.bad
command cp -f /tmp/spectra-plus-rules.bad "$rules"
run_expect 2 "$generator" spectra-propose-plus
assert_contains /tmp/spectra-plus-test.err "source"
eval $restore_rules

run_expect 0 "$generator"
echo "PASS: generator checks"
