#!/usr/bin/env fish

set script_path (status --current-filename)
set script_dir (dirname "$script_path")
set root_dir (realpath "$script_dir/../..")
set rules_file "$script_dir/rules.yaml"
set template_dir "$script_dir/template"
set marker "<!-- Generated by scripts/spectra-plus/generate.fish — DO NOT EDIT MANUALLY -->"

function usage
    echo "Usage: scripts/spectra-plus/generate.fish [skill-name]"
    echo
    echo "Regenerates plus skill SKILL.md files from spectra skills, rules.yaml, and templates."
    echo "Pass one skill name, such as spectra-propose-plus, to regenerate only that output."
end

function die
    set code $argv[1]
    set message $argv[2..-1]
    echo $message >&2
    exit $code
end

function require_yq
    if not command -q yq
        die 2 "rules.yaml parse error: yq is required"
    end
end

function yq_value
    set expression $argv[1]
    yq -r "$expression" "$rules_file"
end

function validate_rules
    require_yq

    if not test -f "$rules_file"
        die 2 "rules.yaml parse error: missing $rules_file"
    end

    if not yq '.' "$rules_file" >/dev/null 2>/tmp/spectra-plus-yq.err
        set err (cat /tmp/spectra-plus-yq.err)
        die 2 "rules.yaml parse error: $err"
    end

    if not yq -e '.skills | type == "!!map"' "$rules_file" >/dev/null
        die 2 "rules.yaml parse error: missing field skills"
    end
end

function validate_skill
    set skill $argv[1]

    for field in source output metadata transformations
        if not yq -e ".skills.\"$skill\" | has(\"$field\")" "$rules_file" >/dev/null
            die 2 "rules.yaml parse error: $skill missing field $field"
        end
    end

    for field in name description
        if not yq -e ".skills.\"$skill\".metadata | has(\"$field\")" "$rules_file" >/dev/null
            die 2 "rules.yaml parse error: $skill metadata missing field $field"
        end
    end

    set count (yq_value ".skills.\"$skill\".transformations | length")
    if test "$count" = "0"
        die 2 "rules.yaml parse error: $skill transformations is empty"
    end

    for index in (seq 0 (math $count - 1))
        for field in target_section operation
            if not yq -e ".skills.\"$skill\".transformations[$index] | has(\"$field\")" "$rules_file" >/dev/null
                die 2 "rules.yaml parse error: $skill transformations[$index] missing field $field"
            end
        end

        set op (yq_value ".skills.\"$skill\".transformations[$index].operation")
        if not contains "$op" replace append remove
            die 2 "rules.yaml parse error: $skill transformations[$index] operation"
        end

        if contains "$op" replace append
            if not yq -e ".skills.\"$skill\".transformations[$index] | has(\"template\")" "$rules_file" >/dev/null
                die 2 "rules.yaml parse error: $skill transformations[$index] missing field template"
            end

            set template_name (yq_value ".skills.\"$skill\".transformations[$index].template")
            if not test -f "$template_dir/$template_name"
                die 3 "missing template file: $template_name"
            end
        end
    end
end

function find_section_end
    set file $argv[1]
    set start $argv[2]

    set end (awk -v start="$start" 'NR > start && ($0 ~ /^[0-9]+\. \*\*/ || $0 ~ /^\*\*/) { print NR - 1; exit } END { if (!found) { } }' "$file")
    if test -z "$end"
        set end (wc -l < "$file" | string trim)
    end
    echo "$end"
end

function apply_transform
    set skill $argv[1]
    set source_path $argv[2]
    set input_path $argv[3]
    set output_path $argv[4]
    set target $argv[5]
    set op $argv[6]
    set template_name $argv[7]

    set start_line (rg -n --fixed-strings "$target" "$input_path" | head -n 1 | cut -d: -f1)
    if test -z "$start_line"
        echo "target_section not found for $skill: $target in $source_path" >&2
        return 1
    end

    set end_line (find_section_end "$input_path" "$start_line")
    set template_path ""
    if contains "$op" replace append
        set template_path "$template_dir/$template_name"
    end

    awk \
        -v start="$start_line" \
        -v end="$end_line" \
        -v op="$op" \
        -v template_path="$template_path" '
        BEGIN {
            if (template_path != "") {
                while ((getline line < template_path) > 0) {
                    template = template line "\n"
                }
                close(template_path)
            }
        }
        NR < start || NR > end {
            print
            next
        }
        NR == start {
            if (op == "replace") {
                printf "%s", template
            } else if (op == "append") {
                print
            }
            next
        }
        NR > start && NR <= end {
            if (op == "append") {
                print
                if (NR == end) {
                    printf "\n%s", template
                }
            }
            next
        }
        ' "$input_path" > "$output_path"
end

function set_frontmatter_field
    set input_path $argv[1]
    set output_path $argv[2]
    set key $argv[3]
    set value $argv[4]

    awk -v key="$key" -v value="$value" '
        BEGIN { in_fm = 0; done = 0 }
        NR == 1 && $0 == "---" { in_fm = 1; print; next }
        in_fm && $0 == "---" {
            if (!done) {
                print key ": " value
            }
            in_fm = 0
            print
            next
        }
        in_fm && $0 ~ "^" key ":" {
            print key ": " value
            done = 1
            next
        }
        { print }
    ' "$input_path" > "$output_path"
end

function validate_generated
    set output_path $argv[1]
    set skill $argv[2]

    for field in name description
        if not rg -q "^$field: .+" "$output_path"
            die 2 "generated frontmatter missing field $field for $skill"
        end
    end
end

function generate_skill
    set skill $argv[1]
    validate_skill "$skill"

    set source_rel (yq_value ".skills.\"$skill\".source")
    set output_rel (yq_value ".skills.\"$skill\".output")
    set source_path "$root_dir/$source_rel"
    set output_path "$root_dir/$output_rel"

    if not test -f "$source_path"
        die 2 "rules.yaml parse error: $skill source not found: $source_rel"
    end

    set work_path (mktemp "/tmp/spectra-plus-$skill.XXXXXX")
    command cp -f "$source_path" "$work_path"

    set count (yq_value ".skills.\"$skill\".transformations | length")
    for index in (seq 0 (math $count - 1))
        set target (yq_value ".skills.\"$skill\".transformations[$index].target_section")
        set op (yq_value ".skills.\"$skill\".transformations[$index].operation")
        set template_name (yq_value ".skills.\"$skill\".transformations[$index].template // \"\"")
        set next_path (mktemp "/tmp/spectra-plus-$skill.XXXXXX")

        apply_transform "$skill" "$source_path" "$work_path" "$next_path" "$target" "$op" "$template_name"
        or exit 1

        command mv -f "$next_path" "$work_path"
    end

    set meta_keys (yq -r ".skills.\"$skill\".metadata | keys | .[]" "$rules_file")
    for key in $meta_keys
        set value (yq_value ".skills.\"$skill\".metadata.\"$key\"")
        set next_path (mktemp "/tmp/spectra-plus-$skill.XXXXXX")
        set_frontmatter_field "$work_path" "$next_path" "$key" "$value"
        command mv -f "$next_path" "$work_path"
    end

    set final_path (mktemp "/tmp/spectra-plus-$skill.XXXXXX")
    printf "%s\n" "$marker" > "$final_path"
    command cat "$work_path" >> "$final_path"
    validate_generated "$final_path" "$skill"

    echo "$skill|$output_path|$final_path"
end

if contains -- --help $argv; or contains -- -h $argv
    usage
    exit 0
end

validate_rules

set requested_skills
if test (count $argv) -gt 0
    if test (count $argv) -ne 1
        usage >&2
        exit 2
    end

    set requested_skills $argv[1]
    if not yq -e ".skills | has(\"$requested_skills\")" "$rules_file" >/dev/null
        die 2 "rules.yaml parse error: unknown skill $requested_skills"
    end
else
    set requested_skills (yq -r '.skills | keys | .[]' "$rules_file")
end

set generated
for skill in $requested_skills
    set generated $generated (generate_skill "$skill")
end

for item in $generated
    set parts (string split '|' "$item")
    set skill $parts[1]
    set output_path $parts[2]
    set final_path $parts[3]
    mkdir -p (dirname "$output_path")
    command mv -f "$final_path" "$output_path"
    echo "wrote $output_path"
    echo "validated $skill"
end
