#!/usr/bin/env fish

set script_path (status --current-filename)
set script_dir (cd (dirname "$script_path"); and pwd)
set root_dir (realpath "$script_dir/../..")
set rules_file "$script_dir/rules.yaml"
set template_dir "$script_dir/template"
set marker "<!-- Generated by scripts/spectra-plus/generate.fish — DO NOT EDIT MANUALLY -->"

function usage
    echo "Usage: generate.fish [--root <dir>] [skill-name]"
    echo
    echo "Regenerates plus skill SKILL.md files from spectra skills, rules.yaml, and templates."
    echo "Pass --root to target a different project directory (defaults to the repo containing this script)."
    echo "Pass one skill name, such as spectra-propose-plus, to regenerate only that output."
    echo "All variants (claude, codex, ...) defined under the skill are produced together."
end

function die
    set code $argv[1]
    set message $argv[2..-1]
    echo $message >&2
    exit $code
end

function require_yq
    if not command -q yq
        die 2 "rules.yaml parse error: yq is required"
    end
end

function yq_value
    set expression $argv[1]
    yq -r "$expression" "$rules_file"
end

function validate_rules
    require_yq

    if not test -f "$rules_file"
        die 2 "rules.yaml parse error: missing $rules_file"
    end

    if not yq '.' "$rules_file" >/dev/null 2>/tmp/spectra-plus-yq.err
        set err (cat /tmp/spectra-plus-yq.err)
        die 2 "rules.yaml parse error: $err"
    end

    if not yq -e '.skills | type == "!!map"' "$rules_file" >/dev/null
        die 2 "rules.yaml parse error: missing field skills"
    end
end

function validate_skill
    set skill $argv[1]

    for field in metadata transformations variants
        if not yq -e ".skills.\"$skill\" | has(\"$field\")" "$rules_file" >/dev/null
            die 2 "rules.yaml parse error: $skill missing field $field"
        end
    end

    for field in name description
        if not yq -e ".skills.\"$skill\".metadata | has(\"$field\")" "$rules_file" >/dev/null
            die 2 "rules.yaml parse error: $skill metadata missing field $field"
        end
    end

    if not yq -e ".skills.\"$skill\".variants | type == \"!!map\"" "$rules_file" >/dev/null
        die 2 "rules.yaml parse error: $skill variants must be a map"
    end

    set variant_count (yq -r ".skills.\"$skill\".variants | length" "$rules_file")
    if test "$variant_count" = "0"
        die 2 "rules.yaml parse error: $skill variants is empty"
    end

    for variant in (yq -r ".skills.\"$skill\".variants | keys | .[]" "$rules_file")
        for field in source output
            if not yq -e ".skills.\"$skill\".variants.\"$variant\" | has(\"$field\")" "$rules_file" >/dev/null
                die 2 "rules.yaml parse error: $skill variant $variant missing field $field"
            end
        end

        if yq -e ".skills.\"$skill\".variants.\"$variant\" | has(\"substitutions\")" "$rules_file" >/dev/null 2>/dev/null
            set sub_count (yq -r ".skills.\"$skill\".variants.\"$variant\".substitutions | length" "$rules_file")
            if test "$sub_count" != "0"
                for sidx in (seq 0 (math $sub_count - 1))
                    for sfield in from to
                        if not yq -e ".skills.\"$skill\".variants.\"$variant\".substitutions[$sidx] | has(\"$sfield\")" "$rules_file" >/dev/null
                            die 2 "rules.yaml parse error: $skill variant $variant substitutions[$sidx] missing field $sfield"
                        end
                    end
                end
            end
        end
    end

    set count (yq_value ".skills.\"$skill\".transformations | length")
    if test "$count" = "0"
        die 2 "rules.yaml parse error: $skill transformations is empty"
    end

    for index in (seq 0 (math $count - 1))
        for field in target_section operation
            if not yq -e ".skills.\"$skill\".transformations[$index] | has(\"$field\")" "$rules_file" >/dev/null
                die 2 "rules.yaml parse error: $skill transformations[$index] missing field $field"
            end
        end

        set op (yq_value ".skills.\"$skill\".transformations[$index].operation")
        if not contains "$op" replace append remove
            die 2 "rules.yaml parse error: $skill transformations[$index] operation"
        end

        if contains "$op" replace append
            if not yq -e ".skills.\"$skill\".transformations[$index] | has(\"template\")" "$rules_file" >/dev/null
                die 2 "rules.yaml parse error: $skill transformations[$index] missing field template"
            end

            set template_name (yq_value ".skills.\"$skill\".transformations[$index].template")
            if not test -f "$template_dir/$template_name"
                die 3 "missing template file: $template_name"
            end
        end
    end
end

function find_section_end
    set file $argv[1]
    set start $argv[2]

    set end (awk -v start="$start" 'NR > start && ($0 ~ /^[0-9]+\. \*\*/ || $0 ~ /^\*\*/) { print NR - 1; exit } END { if (!found) { } }' "$file")
    if test -z "$end"
        set end (wc -l < "$file" | string trim)
    end
    echo "$end"
end

function apply_transform
    set skill $argv[1]
    set source_path $argv[2]
    set input_path $argv[3]
    set output_path $argv[4]
    set target $argv[5]
    set op $argv[6]
    set template_name $argv[7]

    set start_line (rg -n --fixed-strings "$target" "$input_path" | head -n 1 | cut -d: -f1)
    if test -z "$start_line"
        echo "target_section not found for $skill: $target in $source_path" >&2
        return 1
    end

    set end_line (find_section_end "$input_path" "$start_line")
    set template_path ""
    if contains "$op" replace append
        set template_path "$template_dir/$template_name"
    end

    awk \
        -v start="$start_line" \
        -v end="$end_line" \
        -v op="$op" \
        -v template_path="$template_path" '
        BEGIN {
            if (template_path != "") {
                while ((getline line < template_path) > 0) {
                    template = template line "\n"
                }
                close(template_path)
            }
        }
        NR < start || NR > end {
            print
            next
        }
        NR == start {
            if (op == "replace") {
                printf "%s\n", template
            } else if (op == "append") {
                print
            }
            next
        }
        NR > start && NR <= end {
            if (op == "append") {
                print
                if (NR == end) {
                    printf "\n%s\n", template
                }
            }
            next
        }
        ' "$input_path" > "$output_path"
end

function renumber_step_headings
    set input_path $argv[1]
    set output_path $argv[2]

    awk '
        /^[0-9]+\. \*\*/ {
            sub(/^[0-9]+\./, ++step ".")
        }
        { print }
    ' "$input_path" > "$output_path"
end

function set_frontmatter_field
    set input_path $argv[1]
    set output_path $argv[2]
    set key $argv[3]
    set value $argv[4]

    awk -v key="$key" -v value="$value" '
        BEGIN { in_fm = 0; done = 0 }
        NR == 1 && $0 == "---" { in_fm = 1; print; next }
        in_fm && $0 == "---" {
            if (!done) {
                print key ": " value
            }
            in_fm = 0
            print
            next
        }
        in_fm && $0 ~ "^" key ":" {
            print key ": " value
            done = 1
            next
        }
        { print }
    ' "$input_path" > "$output_path"
end

function apply_literal_substitution
    set input_path $argv[1]
    set output_path $argv[2]
    set from $argv[3]
    set to $argv[4]

    awk -v from="$from" -v to="$to" '
        {
            line = $0
            out = ""
            flen = length(from)
            while ((idx = index(line, from)) > 0) {
                out = out substr(line, 1, idx - 1) to
                line = substr(line, idx + flen)
            }
            out = out line
            print out
        }
    ' "$input_path" > "$output_path"
end

function apply_substitutions
    set skill $argv[1]
    set variant $argv[2]
    set input_path $argv[3]
    set output_path $argv[4]

    if not yq -e ".skills.\"$skill\".variants.\"$variant\" | has(\"substitutions\")" "$rules_file" >/dev/null 2>/dev/null
        command cp -f "$input_path" "$output_path"
        return 0
    end

    set sub_count (yq -r ".skills.\"$skill\".variants.\"$variant\".substitutions | length" "$rules_file")
    if test "$sub_count" = "0"
        command cp -f "$input_path" "$output_path"
        return 0
    end

    set work_path (mktemp "/tmp/spectra-plus-sub-$skill-$variant.XXXXXX")
    command cp -f "$input_path" "$work_path"

    for index in (seq 0 (math $sub_count - 1))
        set from (yq_value ".skills.\"$skill\".variants.\"$variant\".substitutions[$index].from")
        set to (yq_value ".skills.\"$skill\".variants.\"$variant\".substitutions[$index].to")
        set next_path (mktemp "/tmp/spectra-plus-sub-$skill-$variant.XXXXXX")
        apply_literal_substitution "$work_path" "$next_path" "$from" "$to"
        command mv -f "$next_path" "$work_path"
    end

    command mv -f "$work_path" "$output_path"
end

function insert_marker_after_frontmatter
    set input_path $argv[1]
    set output_path $argv[2]

    awk -v marker="$marker" '
        BEGIN { fm_state = 0 }
        NR == 1 && $0 == "---" { print; fm_state = 1; next }
        fm_state == 1 && $0 == "---" {
            print
            print marker
            fm_state = 2
            next
        }
        { print }
        END {
            if (fm_state != 2) {
                print "insert_marker_after_frontmatter: no closing --- found" > "/dev/stderr"
                exit 1
            }
        }
    ' "$input_path" > "$output_path"
end

function validate_generated
    set output_path $argv[1]
    set skill $argv[2]

    for field in name description
        if not rg -q "^$field: .+" "$output_path"
            die 2 "generated frontmatter missing field $field for $skill"
        end
    end
end

function generate_skill
    set skill $argv[1]
    validate_skill "$skill"

    set variants (yq -r ".skills.\"$skill\".variants | keys | .[]" "$rules_file")

    for variant in $variants
        set source_rel (yq_value ".skills.\"$skill\".variants.\"$variant\".source")
        set output_rel (yq_value ".skills.\"$skill\".variants.\"$variant\".output")
        set source_path "$root_dir/$source_rel"
        set output_path "$root_dir/$output_rel"

        if not test -f "$source_path"
            die 2 "rules.yaml parse error: $skill variant $variant source not found: $source_rel"
        end

        set work_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")
        command cp -f "$source_path" "$work_path"

        set count (yq_value ".skills.\"$skill\".transformations | length")
        for index in (seq 0 (math $count - 1))
            set target (yq_value ".skills.\"$skill\".transformations[$index].target_section")
            set op (yq_value ".skills.\"$skill\".transformations[$index].operation")
            set template_name (yq_value ".skills.\"$skill\".transformations[$index].template // \"\"")
            set next_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")

            apply_transform "$skill" "$source_path" "$work_path" "$next_path" "$target" "$op" "$template_name"
            or exit 1

            command mv -f "$next_path" "$work_path"
        end

        set renumbered_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")
        renumber_step_headings "$work_path" "$renumbered_path"
        command mv -f "$renumbered_path" "$work_path"

        set meta_keys (yq -r ".skills.\"$skill\".metadata | keys | .[]" "$rules_file")
        for key in $meta_keys
            set value (yq_value ".skills.\"$skill\".metadata.\"$key\"")
            set next_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")
            set_frontmatter_field "$work_path" "$next_path" "$key" "$value"
            command mv -f "$next_path" "$work_path"
        end

        set sub_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")
        apply_substitutions "$skill" "$variant" "$work_path" "$sub_path"
        command rm -f "$work_path"

        set final_path (mktemp "/tmp/spectra-plus-$skill-$variant.XXXXXX")
        insert_marker_after_frontmatter "$sub_path" "$final_path"
        command rm -f "$sub_path"
        validate_generated "$final_path" "$skill"

        echo "$skill|$variant|$output_path|$final_path"
    end
end

set positional
set rest $argv
while test (count $rest) -gt 0
    set arg $rest[1]
    set -e rest[1]

    switch $arg
        case -h --help
            usage
            exit 0
        case --root
            if test (count $rest) -eq 0
                die 2 "--root requires a directory argument"
            end
            set root_dir (realpath $rest[1])
            set -e rest[1]
        case '*'
            set positional $positional $arg
    end
end

validate_rules

set requested_skills
if test (count $positional) -gt 0
    if test (count $positional) -ne 1
        usage >&2
        exit 2
    end

    set requested_skills $positional[1]
    if not yq -e ".skills | has(\"$requested_skills\")" "$rules_file" >/dev/null
        die 2 "rules.yaml parse error: unknown skill $requested_skills"
    end
else
    set requested_skills (yq -r '.skills | keys | .[]' "$rules_file")
end

set generated
for skill in $requested_skills
    set generated $generated (generate_skill "$skill")
end

for item in $generated
    set parts (string split '|' "$item")
    set skill $parts[1]
    set variant $parts[2]
    set output_path $parts[3]
    set final_path $parts[4]
    mkdir -p (dirname "$output_path")
    or die 4 "failed to create output directory for $output_path"
    command mv -f "$final_path" "$output_path"
    or die 4 "failed to write generated skill: $output_path"
    echo "wrote $output_path"
    echo "validated $skill ($variant)"
end
